// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSegYX3L8_408NLbR_PKjm1_jQWIJ0-7w',
    appId: '1:73936367628:web:5d8a3a041f6c643437fe29',
    messagingSenderId: '73936367628',
    projectId: 'venta-de-artesanias-887e1',
    authDomain: 'venta-de-artesanias-887e1.firebaseapp.com',
    storageBucket: 'venta-de-artesanias-887e1.firebasestorage.app',
    measurementId: 'G-YCL17KEJBW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6xzkxUcH9sYA9gqI9lFhoXmfK0C3iOZ8',
    appId: '1:73936367628:android:a1d5d008fa2cb62e37fe29',
    messagingSenderId: '73936367628',
    projectId: 'venta-de-artesanias-887e1',
    storageBucket: 'venta-de-artesanias-887e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLrSTvQ-8ejc2xIIg4vvI5rEhNUVU0Azk',
    appId: '1:73936367628:ios:370cfe756deb20d337fe29',
    messagingSenderId: '73936367628',
    projectId: 'venta-de-artesanias-887e1',
    storageBucket: 'venta-de-artesanias-887e1.firebasestorage.app',
    iosBundleId: 'com.example.ventaDeArtesanias',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLrSTvQ-8ejc2xIIg4vvI5rEhNUVU0Azk',
    appId: '1:73936367628:ios:370cfe756deb20d337fe29',
    messagingSenderId: '73936367628',
    projectId: 'venta-de-artesanias-887e1',
    storageBucket: 'venta-de-artesanias-887e1.firebasestorage.app',
    iosBundleId: 'com.example.ventaDeArtesanias',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSegYX3L8_408NLbR_PKjm1_jQWIJ0-7w',
    appId: '1:73936367628:web:f61215179be6cf7337fe29',
    messagingSenderId: '73936367628',
    projectId: 'venta-de-artesanias-887e1',
    authDomain: 'venta-de-artesanias-887e1.firebaseapp.com',
    storageBucket: 'venta-de-artesanias-887e1.firebasestorage.app',
    measurementId: 'G-V7VLT39BQW',
  );
}
